---
registry_host: intern.sakuracr.jp
api_url: http://192.168.1.12:8080

# Terraform で作成したマネージド DB
db_host: 192.168.1.30
db_port: 5432
db_name: sakuravel_app
db_user: sakuravel_app
db_password: YOUR_MANAGED_DB_PASSWORD

registry_username: YOUR_REGISTRY_USERNAME
registry_password: YOUR_REGISTRY_PASSWORD

node_private_ips:
  node-01: 192.168.1.11
  node-02: 192.168.1.12
  node-03: 192.168.1.13
  node-04: 192.168.1.14
  node-05: 192.168.1.15
